//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
namespace Sitecore.CrmCampaignIntegration.Discovery
{
  using System;
  using System.CodeDom.Compiler;
  using System.ComponentModel;
  using System.Diagnostics;
  using System.Threading;
  using System.Web.Services;
  using System.Web.Services.Description;
  using System.Web.Services.Protocols;
  using System.Xml.Serialization;

  /// <summary>
  /// The crm discovery service.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [WebServiceBinding(Name = "CrmDiscoveryServiceSoap", 
    Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class CrmDiscoveryService : SoapHttpClientProtocol
  {
    #region Delegates

    /// <summary>
    /// The execute completed.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public event ExecuteCompletedEventHandler ExecuteCompleted;

    #endregion

    #region Fields

    /// <summary>
    /// The execute operation completed.
    /// </summary>
    private SendOrPostCallback ExecuteOperationCompleted;

    #endregion

    #region Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="CrmDiscoveryService"/> class. 
    /// The crm discovery service.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public CrmDiscoveryService()
    {
      this.Url = "http://sitecore.test.dk.sitecore.net/MSCrmServices/2007/SPLA/CrmDiscoveryService." + "asmx";
    }

    #endregion

    #region Public methods

    /// <summary>
    /// The begin execute.
    /// </summary>
    /// <param name="Request">
    /// The Request.
    /// </param>
    /// <param name="callback">
    /// The callback.
    /// </param>
    /// <param name="asyncState">
    /// The async State.
    /// </param>
    /// <remarks>
    /// </remarks>
    public IAsyncResult BeginExecute(Request Request, AsyncCallback callback, object asyncState)
    {
      return this.BeginInvoke("Execute", new object[] { Request }, callback, asyncState);
    }

    /// <summary>
    /// The cancel async.
    /// </summary>
    /// <param name="userState">
    /// The user State.
    /// </param>
    /// <remarks>
    /// </remarks>
    public new void CancelAsync(object userState)
    {
      base.CancelAsync(userState);
    }

    /// <summary>
    /// The end execute.
    /// </summary>
    /// <param name="asyncResult">
    /// The async Result.
    /// </param>
    /// <remarks>
    /// </remarks>
    public Response EndExecute(IAsyncResult asyncResult)
    {
      object[] results = this.EndInvoke(asyncResult);
      return (Response)(results[0]);
    }

    /// <summary>
    /// The execute.
    /// </summary>
    /// <param name="Request">
    /// The Request.
    /// </param>
    /// <remarks>
    /// </remarks>
    [SoapDocumentMethod("http://schemas.microsoft.com/crm/2007/CrmDiscoveryService/Execute", 
      RequestNamespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService", 
      ResponseNamespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService", Use = SoapBindingUse.Literal, 
      ParameterStyle = SoapParameterStyle.Wrapped)]
    [return: XmlElement("Response")]
    public Response Execute(Request Request)
    {
      object[] results = this.Invoke("Execute", new object[] { Request });
      return (Response)(results[0]);
    }

    /// <summary>
    /// The execute async.
    /// </summary>
    /// <param name="Request">
    /// The Request.
    /// </param>
    /// <remarks>
    /// </remarks>
    public void ExecuteAsync(Request Request)
    {
      this.ExecuteAsync(Request, null);
    }

    /// <summary>
    /// The execute async.
    /// </summary>
    /// <param name="Request">
    /// The Request.
    /// </param>
    /// <param name="userState">
    /// The user State.
    /// </param>
    /// <remarks>
    /// </remarks>
    public void ExecuteAsync(Request Request, object userState)
    {
      if (this.ExecuteOperationCompleted == null)
      {
        this.ExecuteOperationCompleted = new SendOrPostCallback(this.OnExecuteOperationCompleted);
      }

      this.InvokeAsync("Execute", new object[] { Request }, this.ExecuteOperationCompleted, userState);
    }

    #endregion

    #region Private methods

    /// <summary>
    /// The on execute operation completed.
    /// </summary>
    /// <param name="arg">
    /// The arg.
    /// </param>
    private void OnExecuteOperationCompleted(object arg)
    {
      if (this.ExecuteCompleted != null)
      {
        var invokeArgs = ((InvokeCompletedEventArgs)(arg));
        this.ExecuteCompleted(
          this, 
          new ExecuteCompletedEventArgs(
            invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
      }
    }

    #endregion
  }

  /// <summary>
  /// The request.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [XmlInclude(typeof(IsEndUserNotificationAvailableRequest))]
  [XmlInclude(typeof(RetrievePolicyRequest))]
  [XmlInclude(typeof(RetrieveOrganizationExtendedDetailsRequest))]
  [XmlInclude(typeof(RetrieveCrmTicketRequest))]
  [XmlInclude(typeof(RetrieveOrganizationsRequest))]
  [XmlInclude(typeof(RetrieveClientPatchesRequest))]
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public abstract partial class Request
  {
  }

  /// <summary>
  /// The organization detail.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class OrganizationDetail
  {
    #region Fields

    /// <summary>
    /// The crm metadata service url field.
    /// </summary>
    private string crmMetadataServiceUrlField;

    /// <summary>
    /// The crm service url field.
    /// </summary>
    private string crmServiceUrlField;

    /// <summary>
    /// The friendly name field.
    /// </summary>
    private string friendlyNameField;

    /// <summary>
    /// The organization id field.
    /// </summary>
    private Guid organizationIdField;

    /// <summary>
    /// The organization name field.
    /// </summary>
    private string organizationNameField;

    /// <summary>
    /// The web application url field.
    /// </summary>
    private string webApplicationUrlField;

    #endregion

    #region Public properties

    /// <summary>
    /// The crm metadata service url.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string CrmMetadataServiceUrl
    {
      get
      {
        return this.crmMetadataServiceUrlField;
      }

      set
      {
        this.crmMetadataServiceUrlField = value;
      }
    }

    /// <summary>
    /// The crm service url.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string CrmServiceUrl
    {
      get
      {
        return this.crmServiceUrlField;
      }

      set
      {
        this.crmServiceUrlField = value;
      }
    }

    /// <summary>
    /// The friendly name.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string FriendlyName
    {
      get
      {
        return this.friendlyNameField;
      }

      set
      {
        this.friendlyNameField = value;
      }
    }

    /// <summary>
    /// The organization id.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public Guid OrganizationId
    {
      get
      {
        return this.organizationIdField;
      }

      set
      {
        this.organizationIdField = value;
      }
    }

    /// <summary>
    /// The organization name.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string OrganizationName
    {
      get
      {
        return this.organizationNameField;
      }

      set
      {
        this.organizationNameField = value;
      }
    }

    /// <summary>
    /// The web application url.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string WebApplicationUrl
    {
      get
      {
        return this.webApplicationUrlField;
      }

      set
      {
        this.webApplicationUrlField = value;
      }
    }

    #endregion
  }

  /// <summary>
  /// The client patch info.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class ClientPatchInfo
  {
    #region Fields

    /// <summary>
    /// The depth field.
    /// </summary>
    private int depthField;

    /// <summary>
    /// The description field.
    /// </summary>
    private string descriptionField;

    /// <summary>
    /// The is mandatory field.
    /// </summary>
    private bool isMandatoryField;

    /// <summary>
    /// The link id field.
    /// </summary>
    private string linkIdField;

    /// <summary>
    /// The patch id field.
    /// </summary>
    private Guid patchIdField;

    /// <summary>
    /// The title field.
    /// </summary>
    private string titleField;

    #endregion

    #region Public properties

    /// <summary>
    /// The depth.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public int Depth
    {
      get
      {
        return this.depthField;
      }

      set
      {
        this.depthField = value;
      }
    }

    /// <summary>
    /// The description.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string Description
    {
      get
      {
        return this.descriptionField;
      }

      set
      {
        this.descriptionField = value;
      }
    }

    /// <summary>
    /// The is mandatory.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public bool IsMandatory
    {
      get
      {
        return this.isMandatoryField;
      }

      set
      {
        this.isMandatoryField = value;
      }
    }

    /// <summary>
    /// The link id.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string LinkId
    {
      get
      {
        return this.linkIdField;
      }

      set
      {
        this.linkIdField = value;
      }
    }

    /// <summary>
    /// The patch id.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public Guid PatchId
    {
      get
      {
        return this.patchIdField;
      }

      set
      {
        this.patchIdField = value;
      }
    }

    /// <summary>
    /// The title.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string Title
    {
      get
      {
        return this.titleField;
      }

      set
      {
        this.titleField = value;
      }
    }

    #endregion
  }

  /// <summary>
  /// The organization endpoint.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class OrganizationEndpoint
  {
    #region Fields

    /// <summary>
    /// The authentication type field.
    /// </summary>
    private int authenticationTypeField;

    /// <summary>
    /// The crm metadata service url field.
    /// </summary>
    private string crmMetadataServiceUrlField;

    /// <summary>
    /// The crm service url field.
    /// </summary>
    private string crmServiceUrlField;

    /// <summary>
    /// The web application url field.
    /// </summary>
    private string webApplicationUrlField;

    #endregion

    #region Public properties

    /// <summary>
    /// The authentication type.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public int AuthenticationType
    {
      get
      {
        return this.authenticationTypeField;
      }

      set
      {
        this.authenticationTypeField = value;
      }
    }

    /// <summary>
    /// The crm metadata service url.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string CrmMetadataServiceUrl
    {
      get
      {
        return this.crmMetadataServiceUrlField;
      }

      set
      {
        this.crmMetadataServiceUrlField = value;
      }
    }

    /// <summary>
    /// The crm service url.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string CrmServiceUrl
    {
      get
      {
        return this.crmServiceUrlField;
      }

      set
      {
        this.crmServiceUrlField = value;
      }
    }

    /// <summary>
    /// The web application url.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string WebApplicationUrl
    {
      get
      {
        return this.webApplicationUrlField;
      }

      set
      {
        this.webApplicationUrlField = value;
      }
    }

    #endregion
  }

  /// <summary>
  /// The organization extended detail.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class OrganizationExtendedDetail
  {
    #region Fields

    /// <summary>
    /// The endpoints field.
    /// </summary>
    private OrganizationEndpoint[] endpointsField;

    /// <summary>
    /// The friendly name field.
    /// </summary>
    private string friendlyNameField;

    /// <summary>
    /// The organization id field.
    /// </summary>
    private Guid organizationIdField;

    /// <summary>
    /// The organization name field.
    /// </summary>
    private string organizationNameField;

    #endregion

    #region Public properties

    /// <summary>
    /// The endpoints.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public OrganizationEndpoint[] Endpoints
    {
      get
      {
        return this.endpointsField;
      }

      set
      {
        this.endpointsField = value;
      }
    }

    /// <summary>
    /// The friendly name.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string FriendlyName
    {
      get
      {
        return this.friendlyNameField;
      }

      set
      {
        this.friendlyNameField = value;
      }
    }

    /// <summary>
    /// The organization id.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public Guid OrganizationId
    {
      get
      {
        return this.organizationIdField;
      }

      set
      {
        this.organizationIdField = value;
      }
    }

    /// <summary>
    /// The organization name.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string OrganizationName
    {
      get
      {
        return this.organizationNameField;
      }

      set
      {
        this.organizationNameField = value;
      }
    }

    #endregion
  }

  /// <summary>
  /// The response.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [XmlInclude(typeof(RetrievePolicyResponse))]
  [XmlInclude(typeof(RetrieveCrmTicketResponse))]
  [XmlInclude(typeof(RetrieveOrganizationsResponse))]
  [XmlInclude(typeof(RetrieveClientPatchesResponse))]
  [XmlInclude(typeof(IsEndUserNotificationAvailableResponse))]
  [XmlInclude(typeof(RetrieveOrganizationExtendedDetailsResponse))]
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public abstract partial class Response
  {
  }

  /// <summary>
  /// The retrieve policy response.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class RetrievePolicyResponse : Response
  {
    #region Fields

    /// <summary>
    /// The policy field.
    /// </summary>
    private string policyField;

    #endregion

    #region Public properties

    /// <summary>
    /// The policy.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string Policy
    {
      get
      {
        return this.policyField;
      }

      set
      {
        this.policyField = value;
      }
    }

    #endregion
  }

  /// <summary>
  /// The retrieve crm ticket response.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class RetrieveCrmTicketResponse : Response
  {
    #region Fields

    /// <summary>
    /// The crm ticket field.
    /// </summary>
    private string crmTicketField;

    /// <summary>
    /// The expiration date field.
    /// </summary>
    private string expirationDateField;

    /// <summary>
    /// The organization detail field.
    /// </summary>
    private OrganizationDetail organizationDetailField;

    #endregion

    #region Public properties

    /// <summary>
    /// The crm ticket.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string CrmTicket
    {
      get
      {
        return this.crmTicketField;
      }

      set
      {
        this.crmTicketField = value;
      }
    }

    /// <summary>
    /// The expiration date.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string ExpirationDate
    {
      get
      {
        return this.expirationDateField;
      }

      set
      {
        this.expirationDateField = value;
      }
    }

    /// <summary>
    /// The organization detail.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public OrganizationDetail OrganizationDetail
    {
      get
      {
        return this.organizationDetailField;
      }

      set
      {
        this.organizationDetailField = value;
      }
    }

    #endregion
  }

  /// <summary>
  /// The retrieve organizations response.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class RetrieveOrganizationsResponse : Response
  {
    #region Fields

    /// <summary>
    /// The organization details field.
    /// </summary>
    private OrganizationDetail[] organizationDetailsField;

    #endregion

    #region Public properties

    /// <summary>
    /// The organization details.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public OrganizationDetail[] OrganizationDetails
    {
      get
      {
        return this.organizationDetailsField;
      }

      set
      {
        this.organizationDetailsField = value;
      }
    }

    #endregion
  }

  /// <summary>
  /// The retrieve client patches response.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class RetrieveClientPatchesResponse : Response
  {
    #region Fields

    /// <summary>
    /// The patch info field.
    /// </summary>
    private ClientPatchInfo[] patchInfoField;

    #endregion

    #region Public properties

    /// <summary>
    /// The patch info.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public ClientPatchInfo[] PatchInfo
    {
      get
      {
        return this.patchInfoField;
      }

      set
      {
        this.patchInfoField = value;
      }
    }

    #endregion
  }

  /// <summary>
  /// The is end user notification available response.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class IsEndUserNotificationAvailableResponse : Response
  {
    #region Fields

    /// <summary>
    /// The is end user notification available field.
    /// </summary>
    private bool isEndUserNotificationAvailableField;

    #endregion

    #region Public properties

    /// <summary>
    /// The is end user notification available.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public bool IsEndUserNotificationAvailable
    {
      get
      {
        return this.isEndUserNotificationAvailableField;
      }

      set
      {
        this.isEndUserNotificationAvailableField = value;
      }
    }

    #endregion
  }

  /// <summary>
  /// The retrieve organization extended details response.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class RetrieveOrganizationExtendedDetailsResponse : Response
  {
    #region Fields

    /// <summary>
    /// The organization extended details field.
    /// </summary>
    private OrganizationExtendedDetail[] organizationExtendedDetailsField;

    #endregion

    #region Public properties

    /// <summary>
    /// The organization extended details.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public OrganizationExtendedDetail[] OrganizationExtendedDetails
    {
      get
      {
        return this.organizationExtendedDetailsField;
      }

      set
      {
        this.organizationExtendedDetailsField = value;
      }
    }

    #endregion
  }

  /// <summary>
  /// The client info.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class ClientInfo
  {
    #region Fields

    /// <summary>
    /// The client type field.
    /// </summary>
    private ClientTypes clientTypeField;

    /// <summary>
    /// The crm version field.
    /// </summary>
    private string crmVersionField;

    /// <summary>
    /// The language code field.
    /// </summary>
    private int languageCodeField;

    /// <summary>
    /// The office version field.
    /// </summary>
    private string officeVersionField;

    /// <summary>
    /// The organization id field.
    /// </summary>
    private Guid organizationIdField;

    /// <summary>
    /// The o s version field.
    /// </summary>
    private string oSVersionField;

    /// <summary>
    /// The patch ids field.
    /// </summary>
    private Guid[] patchIdsField;

    /// <summary>
    /// The user id field.
    /// </summary>
    private Guid userIdField;

    #endregion

    #region Public properties

    /// <summary>
    /// The client type.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public ClientTypes ClientType
    {
      get
      {
        return this.clientTypeField;
      }

      set
      {
        this.clientTypeField = value;
      }
    }

    /// <summary>
    /// The crm version.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string CrmVersion
    {
      get
      {
        return this.crmVersionField;
      }

      set
      {
        this.crmVersionField = value;
      }
    }

    /// <summary>
    /// The language code.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public int LanguageCode
    {
      get
      {
        return this.languageCodeField;
      }

      set
      {
        this.languageCodeField = value;
      }
    }

    /// <summary>
    /// The office version.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string OfficeVersion
    {
      get
      {
        return this.officeVersionField;
      }

      set
      {
        this.officeVersionField = value;
      }
    }

    /// <summary>
    /// The organization id.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public Guid OrganizationId
    {
      get
      {
        return this.organizationIdField;
      }

      set
      {
        this.organizationIdField = value;
      }
    }

    /// <summary>
    /// The os version.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string OSVersion
    {
      get
      {
        return this.oSVersionField;
      }

      set
      {
        this.oSVersionField = value;
      }
    }

    /// <summary>
    /// The patch ids.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public Guid[] PatchIds
    {
      get
      {
        return this.patchIdsField;
      }

      set
      {
        this.patchIdsField = value;
      }
    }

    /// <summary>
    /// The user id.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public Guid UserId
    {
      get
      {
        return this.userIdField;
      }

      set
      {
        this.userIdField = value;
      }
    }

    #endregion
  }

  /// <summary>
  /// The client types.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [Flags()]
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  public enum ClientTypes
  {
    /// <summary>
    /// The outlook laptop.
    /// </summary>
    /// <remarks>
    /// </remarks>
    OutlookLaptop = 1, 

    /// <summary>
    /// The outlook desktop.
    /// </summary>
    /// <remarks>
    /// </remarks>
    OutlookDesktop = 2, 

    /// <summary>
    /// The data migration.
    /// </summary>
    /// <remarks>
    /// </remarks>
    DataMigration = 4, 

    /// <summary>
    /// The outlook configuration.
    /// </summary>
    /// <remarks>
    /// </remarks>
    OutlookConfiguration = 8, 

    /// <summary>
    /// The data migration configuration.
    /// </summary>
    /// <remarks>
    /// </remarks>
    DataMigrationConfiguration = 16, 
  }

  /// <summary>
  /// The is end user notification available request.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class IsEndUserNotificationAvailableRequest : Request
  {
    #region Fields

    /// <summary>
    /// The client field.
    /// </summary>
    private EndUserNotificationClient clientField;

    /// <summary>
    /// The organization id field.
    /// </summary>
    private Guid organizationIdField;

    #endregion

    #region Public properties

    /// <summary>
    /// The client.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public EndUserNotificationClient Client
    {
      get
      {
        return this.clientField;
      }

      set
      {
        this.clientField = value;
      }
    }

    /// <summary>
    /// The organization id.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public Guid OrganizationId
    {
      get
      {
        return this.organizationIdField;
      }

      set
      {
        this.organizationIdField = value;
      }
    }

    #endregion
  }

  /// <summary>
  /// The end user notification client.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  public enum EndUserNotificationClient
  {
    /// <summary>
    /// The none.
    /// </summary>
    /// <remarks>
    /// </remarks>
    None, 

    /// <summary>
    /// The web application.
    /// </summary>
    /// <remarks>
    /// </remarks>
    WebApplication, 

    /// <summary>
    /// The portal.
    /// </summary>
    /// <remarks>
    /// </remarks>
    Portal, 

    /// <summary>
    /// The outlook.
    /// </summary>
    /// <remarks>
    /// </remarks>
    Outlook, 

    /// <summary>
    /// The email.
    /// </summary>
    /// <remarks>
    /// </remarks>
    Email, 
  }

  /// <summary>
  /// The retrieve policy request.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class RetrievePolicyRequest : Request
  {
  }

  /// <summary>
  /// The retrieve organization extended details request.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class RetrieveOrganizationExtendedDetailsRequest : Request
  {
    #region Fields

    /// <summary>
    /// The passport ticket field.
    /// </summary>
    private string passportTicketField;

    /// <summary>
    /// The password field.
    /// </summary>
    private string passwordField;

    /// <summary>
    /// The user id field.
    /// </summary>
    private string userIdField;

    #endregion

    #region Public properties

    /// <summary>
    /// The passport ticket.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string PassportTicket
    {
      get
      {
        return this.passportTicketField;
      }

      set
      {
        this.passportTicketField = value;
      }
    }

    /// <summary>
    /// The password.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string Password
    {
      get
      {
        return this.passwordField;
      }

      set
      {
        this.passwordField = value;
      }
    }

    /// <summary>
    /// The user id.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string UserId
    {
      get
      {
        return this.userIdField;
      }

      set
      {
        this.userIdField = value;
      }
    }

    #endregion
  }

  /// <summary>
  /// The retrieve crm ticket request.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class RetrieveCrmTicketRequest : Request
  {
    #region Fields

    /// <summary>
    /// The organization name field.
    /// </summary>
    private string organizationNameField;

    /// <summary>
    /// The passport ticket field.
    /// </summary>
    private string passportTicketField;

    /// <summary>
    /// The password field.
    /// </summary>
    private string passwordField;

    /// <summary>
    /// The user id field.
    /// </summary>
    private string userIdField;

    #endregion

    #region Public properties

    /// <summary>
    /// The organization name.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string OrganizationName
    {
      get
      {
        return this.organizationNameField;
      }

      set
      {
        this.organizationNameField = value;
      }
    }

    /// <summary>
    /// The passport ticket.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string PassportTicket
    {
      get
      {
        return this.passportTicketField;
      }

      set
      {
        this.passportTicketField = value;
      }
    }

    /// <summary>
    /// The password.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string Password
    {
      get
      {
        return this.passwordField;
      }

      set
      {
        this.passwordField = value;
      }
    }

    /// <summary>
    /// The user id.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string UserId
    {
      get
      {
        return this.userIdField;
      }

      set
      {
        this.userIdField = value;
      }
    }

    #endregion
  }

  /// <summary>
  /// The retrieve organizations request.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class RetrieveOrganizationsRequest : Request
  {
    #region Fields

    /// <summary>
    /// The passport ticket field.
    /// </summary>
    private string passportTicketField;

    /// <summary>
    /// The password field.
    /// </summary>
    private string passwordField;

    /// <summary>
    /// The user id field.
    /// </summary>
    private string userIdField;

    #endregion

    #region Public properties

    /// <summary>
    /// The passport ticket.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string PassportTicket
    {
      get
      {
        return this.passportTicketField;
      }

      set
      {
        this.passportTicketField = value;
      }
    }

    /// <summary>
    /// The password.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string Password
    {
      get
      {
        return this.passwordField;
      }

      set
      {
        this.passwordField = value;
      }
    }

    /// <summary>
    /// The user id.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public string UserId
    {
      get
      {
        return this.userIdField;
      }

      set
      {
        this.userIdField = value;
      }
    }

    #endregion
  }

  /// <summary>
  /// The retrieve client patches request.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [Serializable()]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [XmlType(Namespace = "http://schemas.microsoft.com/crm/2007/CrmDiscoveryService")]
  [DebuggerNonUserCode]
  public partial class RetrieveClientPatchesRequest : Request
  {
    #region Fields

    /// <summary>
    /// The client info field.
    /// </summary>
    private ClientInfo clientInfoField;

    #endregion

    #region Public properties

    /// <summary>
    /// The client info.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public ClientInfo ClientInfo
    {
      get
      {
        return this.clientInfoField;
      }

      set
      {
        this.clientInfoField = value;
      }
    }

    #endregion
  }

  /// <summary>
  /// The execute completed event handler.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  public delegate void ExecuteCompletedEventHandler(object sender, ExecuteCompletedEventArgs e);

  /// <summary>
  /// The execute completed event args.
  /// </summary>
  /// <remarks>
  /// </remarks>
  [GeneratedCode("wsdl", "2.0.50727.3038")]
  [DebuggerStepThrough()]
  [DesignerCategory("code")]
  [DebuggerNonUserCode]
  public partial class ExecuteCompletedEventArgs : AsyncCompletedEventArgs
  {
    #region Fields

    /// <summary>
    /// The results.
    /// </summary>
    private object[] results;

    #endregion

    #region Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="ExecuteCompletedEventArgs"/> class.
    /// </summary>
    /// <param name="results">
    /// The results.
    /// </param>
    /// <param name="exception">
    /// The exception.
    /// </param>
    /// <param name="cancelled">
    /// The cancelled.
    /// </param>
    /// <param name="userState">
    /// The user state.
    /// </param>
    internal ExecuteCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState)
      : base(exception, cancelled, userState)
    {
      this.results = results;
    }

    #endregion

    #region Public properties

    /// <summary>
    /// The result.
    /// </summary>
    /// <remarks>
    /// </remarks>
    public Response Result
    {
      get
      {
        this.RaiseExceptionIfNecessary();
        return (Response)(this.results[0]);
      }
    }

    #endregion
  }
}